DELETE FROM Diet;
DELETE FROM FoodItem;

SELECT * FROM Diet;
SELECT * FROM fooditem;

ALTER TABLE FoodItem MODIFY name VARCHAR(255);


ALTER TABLE FoodItem MODIFY name VARCHAR(255);
ALTER TABLE FoodItem MODIFY calories DECIMAL(7,2);
ALTER TABLE FoodItem MODIFY carbs DECIMAL(7,2);
ALTER TABLE FoodItem MODIFY protein DECIMAL(7,2);
ALTER TABLE FoodItem MODIFY fat DECIMAL(7,2);


SHOW COLUMNS FROM FoodItem Like 'name';

USE FitnessTracker;

SELECT * FROM USER;
ORDER BY food_id DESC
LIMIT 10;


SELECT DATABASE();
SHOW TABLES;

SELECT COUNT(*) FROM FoodItem;

SELECT * FROM fooditem
LIMIT 10;

SELECT * FROM fooditem WHERE name LIKE '%chicken%'

SELECT * FROM Diet ORDER BY diet_id DESC LIMIT 10;


DELETE FROM Diet;
DELETE FROM User;

DELETE FROM Diet;
DELETE FROM ExercisePlan;
DELETE FROM User;

-- Optional: reset user_id counter
ALTER TABLE User AUTO_INCREMENT = 1;
