DELETE FROM Diet;
DELETE FROM FoodItem;

SELECT * FROM Diet;
SELECT * FROM fooditem;

ALTER TABLE FoodItem MODIFY name VARCHAR(255);


ALTER TABLE FoodItem MODIFY name VARCHAR(255);
ALTER TABLE FoodItem MODIFY calories DECIMAL(7,2);
ALTER TABLE FoodItem MODIFY protein DECIMAL(6,2);
ALTER TABLE FoodItem MODIFY fat DECIMAL(6,2);
ALTER TABLE FoodItem MODIFY carbs DECIMAL(6,2);
ALTER TABLE FoodItem MODIFY added_sugar DECIMAL(6,2);

SHOW COLUMNS FROM FoodItem Like 'name';